package ISOJ12.Vacuna.presentacion;

import ISOJ12.Vacuna.dominio.controller.GestorVacunacion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daniel
 */
public class RegistrarVacunacion extends javax.swing.JFrame {
    GestorVacunacion gestor = new GestorVacunacion();
    //Esto es para probar solo

    /**
     * Creates new form RegistrarVacunacion
     */
    public RegistrarVacunacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //No modificar
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrelabel = new javax.swing.JLabel();
        nombrePacienteText = new javax.swing.JTextField();
        tipolabel = new javax.swing.JLabel();
        tipovacunatext = new javax.swing.JTextField();
        fechalabel = new javax.swing.JLabel();
        fechaText = new javax.swing.JFormattedTextField();
        aplabel = new javax.swing.JLabel();
        apellidopacientetext = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        atrásButton = new javax.swing.JButton();
        ndosisslider = new javax.swing.JLabel();
        dosisSlider = new javax.swing.JSlider();
        dnilabel = new javax.swing.JLabel();
        grupolabel = new javax.swing.JLabel();
        grupoComboBox = new javax.swing.JComboBox<>();
        dnitext = new javax.swing.JFormattedTextField();
        regionComboBox = new javax.swing.JComboBox<>();
        regLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombrelabel.setText("Nombre del Paciente:");

        tipolabel.setText("Tipo de Vacuna:");

        fechalabel.setText("Fecha (dd.mm.aaaa):");

        fechaText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        fechaText.setToolTipText("");

        aplabel.setText("Apellidos del Paciente:");

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        atrásButton.setText("Atrás");
        atrásButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrásButtonActionPerformed(evt);
            }
        });

        ndosisslider.setText("Nº de dosis a recibir:");

        dosisSlider.setMajorTickSpacing(1);
        dosisSlider.setMaximum(10);
        dosisSlider.setMinimum(1);
        dosisSlider.setPaintLabels(true);
        dosisSlider.setPaintTicks(true);

        dnilabel.setText("DNI del Paciente:");

        grupolabel.setText("Grupo de Prioridad:");

        grupoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ancianos", "Adultos/Adolescentes", "Niños" }));

        try {
            dnitext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dnitext.setToolTipText("");

        regionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asturias", "Galicia", "Cantabria", "La Rioja", "Pais Vasco", "Navarra", "Aragon", "Cataluña", "Castilla y Leon", "Madrid", "Castilla La Mancha", "Comunidad Valenciana", "Murcia", "Andalucia", "Extremadura", "Islas Baleares", "Islas Canarias", "Ceuta", "Melilla" }));

        regLabel.setText("Región:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atrásButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(dosisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grupolabel)
                    .addComponent(aplabel)
                    .addComponent(fechalabel)
                    .addComponent(nombrelabel)
                    .addComponent(dnilabel)
                    .addComponent(tipolabel)
                    .addComponent(regLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombrePacienteText)
                    .addComponent(tipovacunatext)
                    .addComponent(fechaText)
                    .addComponent(apellidopacientetext)
                    .addComponent(grupoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dnitext)
                    .addComponent(regionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ndosisslider)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dnilabel)
                    .addComponent(dnitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrelabel)
                    .addComponent(nombrePacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aplabel)
                    .addComponent(apellidopacientetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipovacunatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipolabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechalabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupolabel)
                    .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ndosisslider, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atrásButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dosisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        Date fecha = null;
        SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
            String dni = dnitext.getText();
            String nombre = nombrePacienteText.getText();
            String apellidos = apellidopacientetext.getText();
            String nombrevacuna = tipovacunatext.getText();
            int numeroDosis = dosisSlider.getValue();
            String grupo = grupoComboBox.getSelectedItem().toString();
            
        try {
            fecha = formatter.parse(fechaText.getText());            
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarVacunacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        gestor.registrarVacunacion(fecha, nombre, apellidos, dni, nombrevacuna, numeroDosis, regionComboBox.getSelectedItem().toString(), grupo);
        
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void atrásButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrásButtonActionPerformed
        PantallaGestionSistemaRegionalSalud pantalla=new PantallaGestionSistemaRegionalSalud(regionComboBox.getSelectedItem().toString());
        pantalla.mostrarGestionRegional();
        this.dispose();
    }//GEN-LAST:event_atrásButtonActionPerformed
    //No modificar
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrarVacunacion().setVisible(true);
        });
    }
    
    public void mostrarRV(){
        this.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidopacientetext;
    private javax.swing.JLabel aplabel;
    private javax.swing.JButton atrásButton;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel dnilabel;
    private javax.swing.JFormattedTextField dnitext;
    private javax.swing.JSlider dosisSlider;
    private javax.swing.JFormattedTextField fechaText;
    private javax.swing.JLabel fechalabel;
    private javax.swing.JComboBox<String> grupoComboBox;
    private javax.swing.JLabel grupolabel;
    private javax.swing.JLabel ndosisslider;
    private javax.swing.JTextField nombrePacienteText;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JLabel regLabel;
    private javax.swing.JComboBox<String> regionComboBox;
    private javax.swing.JLabel tipolabel;
    private javax.swing.JTextField tipovacunatext;
    // End of variables declaration//GEN-END:variables
}
